[pytest]
markers =
    smoke: smoke tests
    regression: regression tests

# Default browser settings (can be overridden via CLI)
addopts = --browser chromium --screenshot only-on-failure --video retain-on-failure
